### ISSUE TITLE
楼主留下的联机版demo已经失效了

### ISSUE THREAD

**Issue by yuyingjian123** [a1098832322/MarketAndroidApp#1]
将后端项目在本机中成功部署后（网页可以访问接口），客户端无法访问到接口，不知道什么原因，baseurl已经修改过了。直接使用默认的网络接口同样访问不到数据

另外您的单机版demo可以运行并显示，但联机版demo也访问不到数据，是接口已经失效了吗？

**Comment by a1098832322** [comment]
> 将后端项目在本机中成功部署后（网页可以访问接口），客户端无法访问到接口，不知道什么原因，baseurl已经修改过了。直接使用默认的网络接口同样访问不到数据
> 
> 另外您的单机版demo可以运行并显示，但联机版demo也访问不到数据，是接口已经失效了吗？

可能是测试机器的Android版本问题，当初开发时是基于Android 7.1开发的，项目中用到的一些开源控件可能对后续高版本系统不兼容。
当初开发时测试6.0-8.0系统都是能用的，后续8.0+的系统有报告说控件加载会有些问题
